### ISSUE TITLE
一部のmswのAPIモックとページのurlが被ってる

### ISSUE THREAD

**Issue by shibayaman** [ecc-proken/GawdiBoard-frontend#8]
## 概要
`/offer/post`などのurlでmswのAPIモックとページで被りが発生してる

## 現在の挙動
募集投稿API`/offer/post`にAPIコールすると募集投稿ページの画面が返却される

## 期待する挙動
APIとページでurlが棲み分けされてる。
(実際のAPIサーバーって`/api`が最初についた気がする？)

**Comment by murata0531** [comment]
サーバのアドレスは全て`/api/~`の形式になってるのでモック(`/mocks/handllers/`)のアドレスの頭に`/api`を追加してください

**Comment by shibayaman** [comment]
#19 で解決しました。
